# Global
global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  ingress:
    onpremiseTls:
      enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "false"
  http_port: 3000
  grpc_port: 5000
  replicaCount: 1  # Сейчас это значение везде равно 1. Если начнет меняться - переносить в Subcharts
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  #    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  resources: {}

# Subcharts
images:
  service: develop
  setup: develop

nameOverride: upload-big-file-elma365
podAnnotations: {}
autoscaling: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity:
  softAntiAffinity: true

upload-big-file-elma365:
  labels:
    app: upload-big-file-elma365

ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
